### ISSUE TITLE
thank ur code

### ISSUE THREAD

**Issue by gaibb** [Livinglist/CoronaCounter#1]
i've finished a ios app showing the real-time infection data, and i am going to do a macos app whose function is same. but i never create a macos project. would u mind me learning from ur code?

**Comment by gaibb** [comment]
well. 24 min passed and my xcode is still fetching alamofire.  what do u use to fetch it?

**Comment by gaibb** [comment]
the code seems there's something wrong. i can compile the code, and it prints something in console, but i cannot find the icon in my status bar!

**Comment by gaibb** [comment]
it just shows "loading" and then disappears

**Comment by Livinglist** [comment]
> it just shows "loading" and then disappears

I’m sorry about the late response, I will look into the issue when I have access to my computer.

**Comment by Livinglist** [comment]
> the code seems there's something wrong. i can compile the code, and it prints something in console, but i cannot find the icon in my status bar!

One thing I noticed is that if your status bar is ‘filled up’ (meaning you have too many icon or something else on your status bar) the newly added icon will be omitted by the system

**Comment by gaibb** [comment]
> > the code seems there's something wrong. i can compile the code, and it prints something in console, but i cannot find the icon in my status bar!
> 
> One thing I noticed is that if your status bar is ‘filled up’ (meaning you have too many icon or something else on your status bar) the newly added icon will be omitted by the system
thanks. i've found it. on my status bar.
and i make some code optimization to make it beautiful. but i can't pull request to ur repository.
to be honest, ur code's readability really needs to be improved 😏

**Comment by Livinglist** [comment]
> > the code seems there's something wrong. i can compile the code, and it prints something in console, but i cannot find the icon in my status bar!
> 
> One thing I noticed is that if your status bar is ‘filled up’ (meaning you have too many icon or something else on your status bar) the newly added icon will be omitted by the system
> thanks. i've found it. on my status bar.
> and i make some code optimization to make it beautiful. but i can't pull request to ur repository.
> to be honest, ur code's readability really needs to be improved 😏

I totally agree. 
I wrote this whole thing in a rush so it is really messed up.
And I just changed the setting of repo so you can try making the pull request again.
